version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - amimart
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
      - JoeyDjr
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
      - JoeyDjr
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - JoeyDjr
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
      - JoeyDjr
    open-pull-requests-limit: 5
