version: '2'
exclude_patterns:
  - '**/*.d.ts'
  - '**/*.spec.ts'
checks:
  method-lines:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 200
