branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 UI changelog"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): perform release ${nextRelease.version}"
