name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # setup
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get current project version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%s')"

      - name: Setup node environment (for building)
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Fetch dependencies
        run: |
          yarn

      - name: Build project
        run: |
          yarn build

      - name: Build Storybook
        run: |
          yarn build-storybook
